# swagger文档配置
knife4j:
  enable: false
  setting:
    language: zh_cn
springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha·
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'admin'
      paths-to-match: '/**'
      packages-to-scan: com.glowxq.system
    - group: 'generator工具'
      paths-to-match: '/**'
      packages-to-scan: com.glowxq.generator
    - group: 'www网站'
      paths-to-match: '/**'
      packages-to-scan: com.glowxq.www
    - group: '微信小程序'
      paths-to-match: '/**'
      packages-to-scan: com.glowxq.applet
